server:
  port: 8181
spring:
  data:
    mongodb:
      database: auth-db
      host: mongodb
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        accountRegistrationChannel:
          destination: accountRegistrations
      default:
        contentType: application/json

