server:
  port: 8181
spring:
  data:
    mongodb:
      uri: mongodb://root:12345@localhost:27017/auth-db?authSource=admin&authMechanism=SCRAM-SHA-1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        accountRegistrationChannel:
          destination: accountRegistrations
      default:
        contentType: application/json

