server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/auth-db
    username: postgres
    password: 12345

  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  application:
    name: AUTH-API

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost