server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/auth-db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        accountRegistrationChannel:
          destination: accountRegistrations
      default:
        contentType: application/json

